Repository SPOTeam/Server, pull requests merged in 2024-11, with the labels that each got.

#247 [FEAT] 네이버 소셜로그인 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/enums/LoginType.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverCallback.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverMember.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverOAuthToken.java
Labels: :+1: feature

#249 [FEAT] 스터디 출석 퀴즈 조회하기 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
Labels: :+1: feature

#250 Deploy 1.3.3
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/config/QuerydslConfig.java
  src/main/java/com/example/spot/config/RegionDataLoader.java
  src/main/java/com/example/spot/config/RestTemplateConfig.java
  src/main/java/com/example/spot/config/S3Config.java
  src/main/java/com/example/spot/config/SentryConfig.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/enums/LoginType.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/MemberScrapRepository.java
  src/main/java/com/example/spot/repository/PostCommentRepository.java
  src/main/java/com/example/spot/repository/querydsl/PostCommentRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/PostCommentRepositoryImpl.java
  src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryService.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverCallback.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverMember.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverOAuthToken.java
Labels: :1st_place_medal: deploy

#253 [MODIFY] 일반 회원가입 이메일 인증 로직 삭제
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
Labels: :question: modify

#254 [FIX] 스터디 일정 버그 수정
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
Labels: :hammer: fix

#256 [MODIFY] 출석 퀴즈에 일정 연결
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Quiz.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/QuizRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
Labels: :question: modify

#257 Deploy 1.3.4
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Quiz.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/QuizRepository.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
Labels: :1st_place_medal: deploy

#260 [FIX] 소셜 로그인 시, 더미 전화번호 값 생기도록 수정
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
Labels: :hammer: fix

#261 [HOTFIX] 소셜 로그인 시, 더미 전화번호 값 생기도록 수정
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy

#258 [FEAT] 구글 소셜로그인 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/spot/security/oauth/CustomOAuthSuccessHandler.java
  src/main/java/com/example/spot/security/oauth/OAuthUserInfoFactory.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/google/CustomOAuth2User.java
  src/main/java/com/example/spot/web/dto/member/google/GoogleExampleResponse.java
  src/main/java/com/example/spot/web/dto/member/google/GoogleUserInfo.java
  src/main/java/com/example/spot/web/dto/member/google/OAuth2UserInfo.java
Labels: :+1: feature

#265 [DOCS] SPOT Server Repo README 업데이트
  README.md
Labels: :book: docs

#266 [FIX] 소셜 로그인 시, 중복 가입 되지 않도록 로직 수정
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/spot/security/oauth/CustomOAuthSuccessHandler.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/google/CustomOAuth2User.java
Labels: :+1: feature, :hammer: fix

#269 [FIX] Period 일정 시작일 종료일 제한
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
Labels: :hammer: fix

#271 Deploy 1.3.6
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
Labels: :1st_place_medal: deploy

#274 [MODIFY] 퀴즈 조회 시 생성일시 반환하도록 수정
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
Labels: :question: modify

#276 [HOTFIX] 퀴즈 조회 시 생성 시점 응답 하도록 코드 추가
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
Labels: :1st_place_medal: deploy
