Repository SPOTeam/Server, pull requests merged in 2024-12, with the labels that each got.

#277 [DOCS] 구글 로그인 관련 Service 코드 주석 추가
  src/main/java/com/example/spot/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/spot/security/oauth/CustomOAuthSuccessHandler.java
  src/main/java/com/example/spot/security/oauth/OAuthUserInfoFactory.java
  src/main/java/com/example/spot/security/oauth/adpter/CustomOAuth2User.java
  src/main/java/com/example/spot/security/oauth/adpter/OAuth2UserInfo.java
  src/main/java/com/example/spot/security/oauth/adpter/google/GoogleUserInfo.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/google/OAuth2UserInfo.java
Labels: :book: docs

#279 [CHORE] 테스트 커버리지 체크 툴 Jacoco 적용
  .gitignore
  build.gradle
Labels: :1234: chore

#280 [TEST] 스터디 조회, 상세 정보 Service 메서드 테스트 코드 작성
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :tada: test

#283 [MODIFY] 네이버 로그인 방식 변경
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
Labels: :question: modify

#284 Deploy 1.3.7
  .gitignore
  build.gradle
  src/main/java/com/example/spot/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/spot/security/oauth/CustomOAuthSuccessHandler.java
  src/main/java/com/example/spot/security/oauth/OAuthUserInfoFactory.java
  src/main/java/com/example/spot/security/oauth/adpter/CustomOAuth2User.java
  src/main/java/com/example/spot/security/oauth/adpter/OAuth2UserInfo.java
  src/main/java/com/example/spot/security/oauth/adpter/google/GoogleUserInfo.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/google/OAuth2UserInfo.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#287 [MODIFY] 네이버 로그인 방식 변경
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverOAuthToken.java
Labels: :question: modify

#288 [HOTFIX] 네이버 로그인 방식 수정
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/naver/NaverOAuthToken.java
Labels: :1st_place_medal: deploy

#289 [TEST] 스터디 일정 API 테스트 코드 작성
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/ScheduleRequestDTO.java
  src/test/java/com/example/spot/service/studyschedule/StudyScheduleCommandServiceTest.java
  src/test/java/com/example/spot/service/studyschedule/StudyScheduleQueryServiceTest.java
Labels: :tada: test
