Repository SPOTeam/Server, pull requests merged in 2024-08, with the labels that each got.

#67 [FEAT] 스터디 게시글 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/domain/PostComment.java
  src/main/java/com/example/spot/domain/enums/Theme.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedComment.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedPost.java
  src/main/java/com/example/spot/domain/mapping/StudyPostImage.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/domain/study/StudyPostComment.java
  src/main/java/com/example/spot/repository/StudyLikedCommentRepository.java
  src/main/java/com/example/spot/repository/StudyLikedPostRepository.java
  src/main/java/com/example/spot/repository/StudyPostCommentRepository.java
  src/main/java/com/example/spot/repository/StudyPostImageRepository.java
  src/main/java/com/example/spot/repository/StudyPostRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyPostRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyPostRepositoryCustomImpl.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/study/request/StudyPostCommentRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyPostCommentResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyPostResDTO.java
Labels: :+1: feature

#68 [FEAT] 마이페이지 및 체크리스트 API 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/MemberThemeRepository.java
  src/main/java/com/example/spot/repository/PreferredRegionRepository.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :+1: feature

#70 [FEAT] JWT 기반 Refresh Token 통한 세션 유지 기능
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/auth/CustomUserDetails.java
  src/main/java/com/example/spot/domain/auth/RefreshToken.java
  src/main/java/com/example/spot/repository/RefreshTokenRepository.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/KaKaoOAuthService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/utils/jwt/JwtTokenProvider.java
  src/main/java/com/example/spot/validation/validator/MemberValidator.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/token/TokenResponseDTO.java
Labels: :+1: feature

#71 [FEAT] 스터디 투표 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/mapping/MemberVote.java
  src/main/java/com/example/spot/domain/study/Option.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/Vote.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/MemberVoteRepository.java
  src/main/java/com/example/spot/repository/OptionRepository.java
  src/main/java/com/example/spot/repository/VoteRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/utils/jwt/JwtTokenProvider.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/ScheduleRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostCommentRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyVoteRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/ScheduleResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyVoteResponseDTO.java
Labels: :+1: feature

#79 [FEAT] 모니터링 도구 추가
  .github/workflows/deploy.yml
  .github/workflows/develop.yml
  build.gradle
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/utils/jwt/JwtTokenProvider.java
Labels: :+1: feature

#82 [fix] deploy workflow 수정
  .github/workflows/deploy.yml
Labels: :hammer: fix

#83 Deploy 1.0.1
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#84 [modify] 내 스터디 API 인증 기능 추가 및 Validation
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Quiz.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/ScheduleRepository.java
  src/main/java/com/example/spot/repository/StudyPostRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistQuiz.java
  src/main/java/com/example/spot/validation/annotation/ExistSchedule.java
  src/main/java/com/example/spot/validation/annotation/ExistStudyLikedComment.java
  src/main/java/com/example/spot/validation/annotation/ExistStudyPost.java
  src/main/java/com/example/spot/validation/annotation/ExistStudyPostComment.java
  src/main/java/com/example/spot/validation/annotation/ExistVote.java
  src/main/java/com/example/spot/validation/annotation/IntSize.java
  src/main/java/com/example/spot/validation/annotation/TextLength.java
  src/main/java/com/example/spot/validation/validator/ExistQuizValidator.java
  src/main/java/com/example/spot/validation/validator/ExistScheduleValidator.java
  src/main/java/com/example/spot/validation/validator/ExistStudyLikedCommentValidator.java
  src/main/java/com/example/spot/validation/validator/ExistStudyPostCommentValidator.java
  src/main/java/com/example/spot/validation/validator/ExistStudyPostValidator.java
  src/main/java/com/example/spot/validation/validator/ExistVoteValidator.java
  src/main/java/com/example/spot/validation/validator/IntSizeValidator.java
  src/main/java/com/example/spot/validation/validator/TextLengthValidator.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/ScheduleRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostCommentRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyVoteRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/ScheduleResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyJoinRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
Labels: :question: modify

#76 [FEAT] 스터디 갤러리 관련 API 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyImageResponseDTO.java
Labels: :+1: feature

#90 Deploy 1.1.1
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/config/SentryConfig.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistPost.java
  src/main/java/com/example/spot/validation/validator/ExistPostValidator.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyImageResponseDTO.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostCreateResponse.java
Labels: :1st_place_medal: deploy

#92 [FEAT] 관리자 권한 부여 및 회원 관련 기능 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/StudyReason.java
  src/main/java/com/example/spot/domain/enums/Reason.java
  src/main/java/com/example/spot/repository/StudyReasonRepository.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#93 Deploy 1.1.2
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/StudyReason.java
  src/main/java/com/example/spot/domain/enums/Reason.java
  src/main/java/com/example/spot/repository/StudyReasonRepository.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :1st_place_medal: deploy

#98 [FEAT] 담당 API에 SecurityUtils 통한 사용자 인증/인가 로직 추가
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
Labels: :+1: feature

#101 [FEAT] 누락된 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/MemberReport.java
  src/main/java/com/example/spot/domain/enums/ReportStatus.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/domain/study/StudyPostReport.java
  src/main/java/com/example/spot/repository/MemberReportRepository.java
  src/main/java/com/example/spot/repository/StudyPostReportRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/IntSize.java
  src/main/java/com/example/spot/validation/validator/IntSizeValidator.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyMemberReportDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyVoteRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :+1: feature

#105 [ FEAT] 스터디 조회 기능 서비스 테스트 코드 작성
  src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :tada: test

#110 [docs] Swagger 명세 수정
  src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
Labels: :book: docs

#111 Deploy 1.2.1
  src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
Labels: :1st_place_medal: deploy

#114 [REFACTOR] 스터디 조회 요구 사항 반영 위한 리팩토링
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :recycle: refactor

#115 Deploy 1.2.2
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#117 [FIX] 스터디 조회 시, totalPage 값 제대로 적용 안되는 오류 수정
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix

#118 Deploy 1.2.3
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#120 [FEAT] To-do list 기능 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/ToDoList.java
  src/main/java/com/example/spot/repository/ToDoListRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistToDoList.java
  src/main/java/com/example/spot/validation/validator/ExistToDoListValidator.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListResponseDTO.java
Labels: :+1: feature

#122 [FEAT] 게시글 좋아요 관련 누락된 기능 구현
  src/main/java/com/example/spot/repository/LikedPostCommentRepository.java
  src/main/java/com/example/spot/repository/LikedPostRepository.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryService.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostQueryService.java
  src/main/java/com/example/spot/service/post/LikedPostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/post/CommentCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :+1: feature

#123 Deploy 1.2.4
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/ToDoList.java
  src/main/java/com/example/spot/repository/LikedPostCommentRepository.java
  src/main/java/com/example/spot/repository/LikedPostRepository.java
  src/main/java/com/example/spot/repository/ToDoListRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryService.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostQueryService.java
  src/main/java/com/example/spot/service/post/LikedPostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistToDoList.java
  src/main/java/com/example/spot/validation/validator/ExistToDoListValidator.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListResponseDTO.java
  src/main/java/com/example/spot/web/dto/post/CommentCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :1st_place_medal: deploy

#125 [ FEAT] 이미지 업로드 API 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/web/controller/UtilController.java
  src/main/java/com/example/spot/web/dto/util/response/ImageResponse.java
Labels: :+1: feature

#126 Deploy 1.2.5
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/web/controller/UtilController.java
  src/main/java/com/example/spot/web/dto/util/response/ImageResponse.java
Labels: :1st_place_medal: deploy

#128 [REFACTOR] 스터디 정보 조회 시, 최대 인원 수 정보 반환 하도록 수정
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :recycle: refactor

#134 [modify] 내 스터디 게시글 조회 기능 수정
  src/main/java/com/example/spot/repository/StudyLikedPostRepository.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :question: modify

#133 [FEAT] 알림 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Notification.java
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/domain/enums/NotifyType.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/NotificationRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandService.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryService.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
  src/main/resources/data/region_data.tsv
Labels: :+1: feature

#138 Deploy 1.2.7
  README.md
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
Labels: :1st_place_medal: deploy

#140 [REFACTOR] 스터디 조회 시 반환 값에 스터디 목표 추가
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :recycle: refactor

#141 Deploy 1.2.8
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :1st_place_medal: deploy

#143 [REFACTOR] 스터디 멤버가 아니라도 스터디 참여 멤버 조회 가능하도록 기능 수정
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
Labels: :recycle: refactor

#144 Deploy 1.2.9
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
Labels: :1st_place_medal: deploy

#146 [REFACTOR] 스터디의 멤버 카운트 증가 로직 수정
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyMemberResponseDTO.java
Labels: :recycle: refactor

#147 Deploy 1.2.10
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyMemberResponseDTO.java
Labels: :1st_place_medal: deploy

#149 [FIX] memberCount 및 isLike 조회 시 반영 안되는 오류 수정
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix

#152 [FIX] isLike 조회 시, status가 LIKED인 경우만 필터링 하도록 수정
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :hammer: fix

#153 [HOTFIX] isLiked 값 변경 안되는 오류 수정
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :1st_place_medal: deploy

#155 [FIX] 찜한 스터디 조회 시, 비활성화 된 찜 스터디도 조회 되는 오류 수정
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix

#156 [HOTFIX] 찜한 스터디 조회 시, 비활성화 된 찜 스터디도 조회 되는 오류 수정
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix, :1st_place_medal: deploy

#158 [REFACTOR] 스터디 관련 요구사항 반영
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/NotificationRepository.java
  src/main/java/com/example/spot/repository/RefreshTokenRepository.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :recycle: refactor

#159 [HOTFIX] 스터디 관련 요구사항 반영
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/NotificationRepository.java
  src/main/java/com/example/spot/repository/RefreshTokenRepository.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :recycle: refactor, :hammer: fix, :1st_place_medal: deploy

#161 [FIX] 스터디 상세 조회 시, 조회 수 오르도록 수정
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
Labels: :hammer: fix

#162 [HOTFIX] 스터디 상세 조회 시, 조회 수 오르도록 수정
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy

#166 [FEAT] 전체 스터디 조회 API 구현
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :+1: feature

#168 [fix] 스터디 게시글 기능 오류 수정
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/StudyLikedPostRepository.java
  src/main/java/com/example/spot/repository/StudyPostCommentRepository.java
  src/main/java/com/example/spot/repository/StudyPostImageRepository.java
  src/main/java/com/example/spot/repository/StudyPostReportRepository.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
Labels: :-1: bug, :hammer: fix

#169 Deploy 1.2.11
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/repository/StudyLikedPostRepository.java
  src/main/java/com/example/spot/repository/StudyPostCommentRepository.java
  src/main/java/com/example/spot/repository/StudyPostImageRepository.java
  src/main/java/com/example/spot/repository/StudyPostReportRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#171 [FIX] 찜 한 스터디 count 로직 수정
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix

#172 [MODIFY] 스터디 게시글 댓글 수 조회 방식 변경 & DTO에 이름 추가
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :question: modify

#164 [REFACTOR] 게시글 및 댓글 조회 시 작성자 프로필 이미지 반환하도록 수정
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :recycle: refactor

#173 [HOTFIX] 게시글 및 댓글 요구사항 반영
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
  src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :hammer: fix, :1st_place_medal: deploy

#174 [modify] PostDetailDTO 수정 (프로필 이미지 추가)
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :question: modify

#176 [FEAT] 누락된 스터디 조회 API 구현
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
Labels: :+1: feature

#177 [HOTFIX] 스터디 게시글 조회 시, 댓글 갯수 반영 안되던 오류 수정
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :hammer: fix, :1st_place_medal: deploy

#178 [modify] Modify DefaultImage Value
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
Labels: :question: modify

#179 [HOTFIX] 기본 이미지 관련 오류 수정
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy

#181 [FEAT] 검색 조건 제외한 전체 스터디 조회 API 구현
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
Labels: :+1: feature

#182 Deploy 1.2.13
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
Labels: :1st_place_medal: deploy

#184 [fix] 댓글순 인기글 반환 안되는 오류 해결
  src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
Labels: :hammer: fix

#185 [HOTFIX] 댓글 순 인기글 반환 안되는 오류 해결
  src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy

#187 [FIX] 모집 중 스터디 조회 시, 완료 조건 누락된 오류 수정
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
Labels: :hammer: fix

#188 [HOTFIX] 스터디 조회 조건 누락된 오류 수정
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy

#190 [fix] 모집 중 스터디 조회 시, 완료 조건 누락된 오류 수정
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
Labels: :hammer: fix

#191 [HOTFIX] 스터디 조회 누락 조건 추가
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
Labels: :hammer: fix, :1st_place_medal: deploy
