Repository SPOTeam/Server, pull requests merged in 2024-07, with the labels that each got.

#3 [feat] 스터디 관련 엔티티 생성 및 연관관계 매핑
  .github/workflows/deploy.yml
  .github/workflows/develop.yml
  build.gradle
  src/main/java/com/example/SpotApplication.java
  src/main/java/com/example/controller/TestController.java
  src/main/java/com/example/domain/enums/Gender.java
  src/main/java/com/example/domain/enums/Status.java
  src/main/java/com/example/domain/enums/StudyState.java
  src/main/java/com/example/domain/enums/Theme.java
  src/main/java/com/example/domain/mapping/MemberVote.java
  src/main/java/com/example/domain/mapping/StudyLikedComment.java
  src/main/java/com/example/domain/mapping/StudyLikedPost.java
  src/main/java/com/example/domain/mapping/StudyPostImage.java
  src/main/java/com/example/domain/study/Option.java
  src/main/java/com/example/domain/study/Schedule.java
  src/main/java/com/example/domain/study/Study.java
  src/main/java/com/example/domain/study/StudyPost.java
  src/main/java/com/example/domain/study/StudyPostComment.java
  src/main/java/com/example/domain/study/Vote.java
Labels: :+1: feature

#13 [CHORE] Add Swagger Dependency and Config
  build.gradle
  src/main/java/com/example/SwaggerConfig.java
  src/main/java/com/example/spot/controller/MemberController.java
  src/main/java/com/example/spot/controller/NotificationController.java
  src/main/java/com/example/spot/controller/PostController.java
  src/main/java/com/example/spot/controller/SearchController.java
  src/main/java/com/example/spot/controller/SignInController.java
  src/main/java/com/example/spot/controller/StudyController.java
Labels: :1234: chore

#12 [FEAT] Entity 및 매핑 테이블 생성 by kyoungmin
  src/main/java/com/example/spot/domain/LikedPost.java
  src/main/java/com/example/spot/domain/LikedPostComment.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/domain/PostComment.java
  src/main/java/com/example/spot/domain/PostImage.java
  src/main/java/com/example/spot/domain/PostReport.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/enums/Board.java
  src/main/java/com/example/spot/domain/enums/PostStatus.java
  src/main/java/com/example/spot/domain/mapping/MemberScrap.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/RegionStudy.java
Labels: :+1: feature

#14 [FEAT] API 응답 통일 코드 구현
  build.gradle
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/BaseCode.java
  src/main/java/com/example/spot/api/code/BaseErrorCode.java
  src/main/java/com/example/spot/api/code/ErrorReasonDTO.java
  src/main/java/com/example/spot/api/code/ReasonDTO.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/api/exception/GeneralException.java
Labels: :+1: feature

#18 [docs] Swagger 스터디 조회 관련 기능 API 명세서 작성
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/controller/SearchController.java
  src/main/java/com/example/spot/domain/LikedPostComment.java
  src/main/java/com/example/spot/domain/enums/StudySortBy.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/SignInController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/controller/TestController.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
Labels: :book: docs, :+1: feature, :recycle: refactor

#21 [modify] StudyPostComment 엔티티에 대댓글 관련 컬럼 추가
  src/main/java/com/example/spot/domain/study/StudyPostComment.java
Labels: :question: modify

#23 [docs] Swagger 스터디 관련 기능 API 명세서 작성
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
Labels: :book: docs

#24 [docs] Swagger 게시판 관련 기능 API 명세서 작성
  src/main/java/com/example/spot/domain/enums/Board.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/CommentResponse.java
  src/main/java/com/example/spot/web/dto/post/PostBest5DetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostBest5Response.java
  src/main/java/com/example/spot/web/dto/post/PostBoard5Response.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostHomeResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
  src/main/java/com/example/spot/web/service/PostService.java
Labels: :book: docs

#26 Deploy 0.2
  build.gradle
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/BaseCode.java
  src/main/java/com/example/spot/api/code/BaseErrorCode.java
  src/main/java/com/example/spot/api/code/ErrorReasonDTO.java
  src/main/java/com/example/spot/api/code/ReasonDTO.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/api/exception/GeneralException.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/domain/LikedPost.java
  src/main/java/com/example/spot/domain/LikedPostComment.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/domain/PostComment.java
  src/main/java/com/example/spot/domain/PostImage.java
  src/main/java/com/example/spot/domain/PostReport.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/domain/enums/Board.java
  src/main/java/com/example/spot/domain/enums/PostStatus.java
  src/main/java/com/example/spot/domain/enums/StudySortBy.java
  src/main/java/com/example/spot/domain/mapping/MemberScrap.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/RegionStudy.java
  src/main/java/com/example/spot/domain/study/StudyPostComment.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/SignInController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/controller/TestController.java
  src/main/java/com/example/spot/web/dto/post/CommentResponse.java
  src/main/java/com/example/spot/web/dto/post/PostBest5DetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostBest5Response.java
  src/main/java/com/example/spot/web/dto/post/PostBoard5Response.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostHomeResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
  src/main/java/com/example/spot/web/service/PostService.java
Labels: :1st_place_medal: deploy

#32 [feat] 에러 핸들러 뼈대 코드 생성
  src/main/java/com/example/spot/api/exception/handler/MemberHandler.java
  src/main/java/com/example/spot/api/exception/handler/NotificationHandler.java
  src/main/java/com/example/spot/api/exception/handler/PostHandler.java
  src/main/java/com/example/spot/api/exception/handler/StudyHandler.java
Labels: :+1: feature

#34 [FEAT] TSV 파일 기반 Region 테이블 초기 데이터 삽입 기능 추가
  build.gradle
  src/main/java/com/example/spot/config/RegionDataLoader.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/repository/RegionRepository.java
  src/main/resources/data/region_data.tsv
Labels: :+1: feature

#36 [docs] Swagger 스터디 관련 기능 API 명세서 작성
  build.gradle
  src/main/java/com/example/spot/web/controller/NotificationController.java
Labels: :book: docs

#38 [FEAT] 스터디 생성/참여 관련 API 구현
  src/main/java/com/example/SpotApplication.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/Theme.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/mapping/MemberTheme.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/RegionStudy.java
  src/main/java/com/example/spot/domain/mapping/StudyTheme.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/RegionRepository.java
  src/main/java/com/example/spot/repository/RegionStudyRepository.java
  src/main/java/com/example/spot/repository/StudyRepository.java
  src/main/java/com/example/spot/repository/StudyThemeRepository.java
  src/main/java/com/example/spot/repository/ThemeRepository.java
  src/main/java/com/example/spot/service/post/PostService.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/request/StudyJoinRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyJoinResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyRegisterResponseDTO.java
Labels: :+1: feature

#42 [modify] Validation 적용 및 ExceptionAdvice 수정
  .gitignore
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/api/exception/GeneralException.java
  src/main/java/com/example/spot/api/exception/handler/MemberHandler.java
  src/main/java/com/example/spot/api/exception/handler/NotificationHandler.java
  src/main/java/com/example/spot/api/exception/handler/PostHandler.java
  src/main/java/com/example/spot/api/exception/handler/StudyHandler.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/web/controller/TestController.java
Labels: :question: modify

#40 [FEAT] 스터디 조회 관련 API 구현
  .gitignore
  build.gradle
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/config/EntitySpecification.java
  src/main/java/com/example/spot/config/QuerydslConfig.java
  src/main/java/com/example/spot/config/RegionDataLoader.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Theme.java
  src/main/java/com/example/spot/domain/enums/StudySortBy.java
  src/main/java/com/example/spot/domain/mapping/MemberTheme.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/PreferredStudy.java
  src/main/java/com/example/spot/domain/mapping/RegionStudy.java
  src/main/java/com/example/spot/domain/mapping/StudyTheme.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/MemberThemeRepository.java
  src/main/java/com/example/spot/repository/PreferredRegionRepository.java
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/repository/RegionRepository.java
  src/main/java/com/example/spot/repository/RegionStudyRepository.java
  src/main/java/com/example/spot/repository/StudyRepository.java
  src/main/java/com/example/spot/repository/StudyThemeRepository.java
  src/main/java/com/example/spot/repository/ThemeRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/post/PostService.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistMember.java
  src/main/java/com/example/spot/validation/annotation/ExistRegion.java
  src/main/java/com/example/spot/validation/annotation/ExistTheme.java
  src/main/java/com/example/spot/validation/validator/ExistMemberValidator.java
  src/main/java/com/example/spot/validation/validator/ExistRegionValidator.java
  src/main/java/com/example/spot/validation/validator/ExistThemeValidator.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :+1: feature

#47 [FEAT] 내 스터디 관련 조회 API 구현
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/StudyReason.java
  src/main/java/com/example/spot/domain/Theme.java
  src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/mapping/MemberTheme.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/StudyTheme.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/validation/validator/ExistMemberValidator.java
  src/main/java/com/example/spot/validation/validator/ExistThemeValidator.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :+1: feature

#43 [FEAT] 알림 조회 관련 API 기능 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Notification.java
  src/main/java/com/example/spot/repository/NotificationRepository.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/dto/notification/NotificationRequestDTO.java
  src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
  src/main/java/com/example/spot/web/service/notification/NotificationCommandService.java
  src/main/java/com/example/spot/web/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/web/service/notification/NotificationQueryService.java
  src/main/java/com/example/spot/web/service/notification/NotificationQueryServiceImpl.java
Labels: :+1: feature

#50 [FEAT] 내 스터디 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/EntitySpecification.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/enums/StudyLikeStatus.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/mapping/PreferredStudy.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/PreferredStudyRepository.java
  src/main/java/com/example/spot/repository/ScheduleRepository.java
  src/main/java/com/example/spot/repository/StudyPostRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/validation/annotation/ExistStudy.java
  src/main/java/com/example/spot/validation/validator/ExistStudyValidator.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyApplyResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyLikeResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyMemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyPostResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyScheduleResponseDTO.java
Labels: :+1: feature

#54 [REFACTOR] 조회 및 스터디 API 코드 리팩토링
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/mapping/PreferredStudy.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/RegionRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandService.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryService.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
Labels: :recycle: refactor

#51 [FEAT] 게시글 CRUD 관련 API 구현
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/domain/PostComment.java
  src/main/java/com/example/spot/repository/PostRepository.java
  src/main/java/com/example/spot/service/post/PostCommandService.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryService.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/CommentResponse.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostCreateResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostPagingResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
Labels: :+1: feature

#56 [feat] S3 서비스 세팅
  build.gradle
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/exception/handler/S3Handler.java
  src/main/java/com/example/spot/config/S3Config.java
  src/main/java/com/example/spot/service/s3/S3ImageService.java
Labels: :+1: feature

#58 [feat] 스터디 일정 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/enums/Period.java
  src/main/java/com/example/spot/domain/mapping/MemberTheme.java
  src/main/java/com/example/spot/domain/mapping/PreferredRegion.java
  src/main/java/com/example/spot/domain/mapping/RegionStudy.java
  src/main/java/com/example/spot/domain/mapping/StudyTheme.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/ScheduleRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/study/request/ScheduleRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/ScheduleResponseDTO.java
Labels: :+1: feature

#65 [FEAT] 카카오 소셜 로그인 기능 구현
  build.gradle
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/RestTemplateConfig.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/enums/Carrier.java
  src/main/java/com/example/spot/domain/enums/JwtValidationType.java
  src/main/java/com/example/spot/domain/enums/LoginType.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/service/member/MemberService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/member/oauth/KaKaoOAuthService.java
  src/main/java/com/example/spot/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/utils/jwt/JwtTokenProvider.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SignInController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/kakao/KaKaoOAuthToken.java
  src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
Labels: :+1: feature
