Repository SPOTeam/Server, pull requests merged in 2024-10, with the labels that each got.

#211 [FIX] 스터디 조회 관련 검증 로직 수정
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :book: docs, :hammer: fix

#214 [Modify] 회원가입 인증 방식 변경
  build.gradle
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/auth/TempUserDetails.java
  src/main/java/com/example/spot/domain/auth/VerificationCode.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepository.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/UserDetailsServiceCustom.java
  src/main/java/com/example/spot/service/member/UserDetailsServiceCustomImpl.java
  src/main/java/com/example/spot/service/message/MailService.java
  src/main/java/com/example/spot/service/message/MailServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/token/TokenResponseDTO.java
  src/main/resources/templates/MailForm.html
Labels: :question: modify

#216 [DOCS] 알림, 인증, 스터디 조회 Service 코드 주석 추가
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/KaKaoOAuthService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
Labels: :book: docs, :recycle: refactor

#221 Deploy 1.3.1
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/ISSUE_TEMPLATE/modify.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/workflows/issue.yml
  README.md
  build.gradle
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/auth/TempUserDetails.java
  src/main/java/com/example/spot/domain/auth/VerificationCode.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepository.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/KaKaoOAuthService.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/member/UserDetailsServiceCustom.java
  src/main/java/com/example/spot/service/member/UserDetailsServiceCustomImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/message/MailService.java
  src/main/java/com/example/spot/service/message/MailServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/token/TokenResponseDTO.java
  src/main/resources/templates/MailForm.html
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#223 [HOTFIX] 소셜 로그인 및 테스트 회원 생성 시, 닉네임도 처리 하도록 수정
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
Labels: :hammer: fix

#224 [HOTFIX] 소셜 로그인 및 테스트 회원 생성 시, 닉네임도 처리 하도록 수정
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
Labels: :1st_place_medal: deploy

#226 [MODIFY] 회원가입 생년월일 성별 정보 추가
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
Labels: :question: modify

#225 [FEAT] 인기 검색어 조회 기능 구현
  build.gradle
  src/main/java/com/example/SpotApplication.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/RedisConfig.java
  src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
Labels: :+1: feature

#229 [FEAT] 아이디/비밀번호 찾기 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#232 Deploy 1.3.2
  build.gradle
  src/main/java/com/example/SpotApplication.java
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/RedisConfig.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
  src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#237 [HOTFIX] 카카오 소셜 로그인 시, 전화번호 중복 오류 수정
  src/main/java/com/example/spot/security/utils/MemberUtils.java
  src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
Labels: :1st_place_medal: deploy

#233 [DOCS] 스터디 게시글 관련 Service 코드 주석 추가
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
Labels: :book: docs

#234 [DOCS] Util 메서드 및 설정 파일 주석 작성
  src/main/java/com/example/spot/api/ApiResponse.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/config/QuerydslConfig.java
  src/main/java/com/example/spot/config/RegionDataLoader.java
  src/main/java/com/example/spot/config/RestTemplateConfig.java
  src/main/java/com/example/spot/config/S3Config.java
  src/main/java/com/example/spot/config/SentryConfig.java
  src/main/java/com/example/spot/config/SwaggerConfig.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java
  src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
  src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
Labels: :book: docs

#238 [DOCS] 일반 로그인 관련 Service 코드 주석 추가
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
Labels: :book: docs

#240 [DOCS] 게시글 관련 Service 코드 주석 추가
  src/main/java/com/example/spot/repository/MemberScrapRepository.java
  src/main/java/com/example/spot/repository/PostCommentRepository.java
  src/main/java/com/example/spot/repository/querydsl/PostCommentRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/PostCommentRepositoryImpl.java
  src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/LikedPostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/service/post/PostService.java
Labels: :book: docs

#241 [DOCS] 스터디 내부 기능 Service 코드 주석 추가
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
Labels: :book: docs

#242 [MODIFY] 게시글 조회수 구현 방식 변경
  src/main/java/com/example/spot/service/post/PostQueryService.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
Labels: :question: modify

#244 [FEAT] 아이디 & 이메일 사용 가능 여부 확인하는 기능 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature
