Repository SPOTeam/Server, pull requests merged in 2025-03, with the labels that each got.

#350 [FEAT] 스터디 게시글 편집 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/StudyPostImageRepository.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
Labels: :+1: feature

#351 [MODIFY] 스터디 게시글 조회 시 작성 여부 반환
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :question: modify

#352 Deploy 1.3.14
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/repository/StudyPostImageRepository.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
Labels: :1st_place_medal: deploy

#353 [REFACTOR] 스터디 필터링 및 키워드 검색 성능 개선
  build.gradle
  src/main/java/com/example/spot/config/ApiLoggingInterceptor.java
  src/main/java/com/example/spot/config/WebConfig.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  src/main/resources/spy.properties
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :+1: feature, :recycle: refactor, :tada: test

#356 [REFACTOR] 스터디 참여 이유 관련 수정사항 반영
  src/main/java/com/example/spot/domain/enums/Reason.java
  src/main/java/com/example/spot/web/controller/MemberController.java
Labels: :recycle: refactor

#357 Deploy 1.4.1
  build.gradle
  src/main/java/com/example/spot/config/ApiLoggingInterceptor.java
  src/main/java/com/example/spot/config/WebConfig.java
  src/main/java/com/example/spot/domain/enums/Reason.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  src/main/resources/spy.properties
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#360 Deploy 1.4.2
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/PostReport.java
  src/main/java/com/example/spot/repository/PostReportRepository.java
  src/main/java/com/example/spot/service/post/PostCommandService.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/PostReportResponse.java
Labels: :1st_place_medal: deploy

#361 [FEAT] 회원탈퇴 기능 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/RefreshTokenRepository.java
  src/main/java/com/example/spot/scheduler/MemberRemovalScheduler.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/admin/AdminService.java
  src/main/java/com/example/spot/service/admin/AdminServiceImpl.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/dto/admin/AdminResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#363 [FEAT] 스터디 호스트 여부 조회 기능 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyMemberResDTO.java
Labels: :+1: feature

#367 [FIX] 호스트 회원탈퇴 예외처리 추가
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
Labels: :hammer: fix

#368 [MODIFY] 스터디 끝내기 성과 로직 추가
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
Labels: :question: modify

#369 [FEAT] 스터디 호스트의 스터디 탈퇴 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyHostWithdrawRequestDTO.java
Labels: :+1: feature

#370 Deploy 1.4.3
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/RefreshTokenRepository.java
  src/main/java/com/example/spot/scheduler/MemberRemovalScheduler.java
  src/main/java/com/example/spot/security/utils/SecurityUtils.java
  src/main/java/com/example/spot/service/admin/AdminService.java
  src/main/java/com/example/spot/service/admin/AdminServiceImpl.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/AdminController.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/dto/admin/AdminResponseDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyHostWithdrawRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyMemberResDTO.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
Labels: :1st_place_medal: deploy

#372 [FEAT] 스터디 정보 수정 및 관련 API 구현
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/RegionStudyRepository.java
  src/main/java/com/example/spot/repository/StudyThemeRepository.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :+1: feature

#373 Deploy 1.4.4
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/RegionStudyRepository.java
  src/main/java/com/example/spot/repository/StudyThemeRepository.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
Labels: :1st_place_medal: deploy

#376 Deploy 1.4.5
  src/main/java/com/example/spot/repository/MemberStudyRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryService.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/NotificationController.java
  src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
  src/test/java/com/example/spot/service/notification/NotificationQueryServiceTest.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy
