Repository SPOTeam/Server, pull requests merged in 2025-02, with the labels that each got.

#333 [MODIFY] 게시글 단건 조회 시 작성자 확인 필드 추가
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :question: modify

#336 Deploy 1.3.12
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :1st_place_medal: deploy

#338 [REFACTOR] 추천 스터디 조회 내부 로직 변경
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :recycle: refactor

#339 [TEST] 스터디 게시글 API 테스트 코드 작성
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedComment.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedPost.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/domain/study/StudyPostComment.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostCommentRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
  src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
  src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :tada: test

#341 [MODIFY] 다가오는 스터디 모임 일정 조회 API 수정
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/study/response/StudyScheduleResponseDTO.java
Labels: :question: modify

#342 [TEST] 진행중인 스터디 API 테스트 코드 작성
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
Labels: :tada: test

#343 Deploy 1.3.13
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedComment.java
  src/main/java/com/example/spot/domain/mapping/StudyLikedPost.java
  src/main/java/com/example/spot/domain/study/Study.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/domain/study/StudyPostComment.java
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostCommentRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyScheduleResponseDTO.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
  src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
  src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :1st_place_medal: deploy

#345 [FIX] 인증메일 Null Pointer 오류 해결
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/auth/VerificationCode.java
  src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
Labels: :hammer: fix
