Repository SPOTeam/Server, pull requests merged in 2025-04, with the labels that each got.

#382 Deploy 1.5.1
  src/main/java/com/example/spot/domain/Member.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
Labels: :1st_place_medal: deploy

#386 Deploy 1.5.2
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/domain/LikedPost.java
  src/main/java/com/example/spot/domain/LikedPostComment.java
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/domain/common/BaseEntity.java
  src/main/java/com/example/spot/domain/mapping/MemberScrap.java
  src/main/java/com/example/spot/repository/PostReportRepository.java
  src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/CommentCreateRequest.java
  src/main/java/com/example/spot/web/dto/post/CommentCreateResponse.java
  src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostBest5DetailResponse.java
  src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
  src/test/java/com/example/spot/service/post/PostCommandServiceTest.java
  src/test/java/com/example/spot/service/post/PostQueryServiceTest.java
Labels: :1st_place_medal: deploy

#388 [MODIFY] 게시글 조회 시 게시글 정렬 순서 변경
  src/main/java/com/example/spot/repository/PostRepository.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/test/java/com/example/spot/service/post/PostQueryServiceTest.java
Labels: :question: modify

#390 Deploy 1.5.3
  src/main/java/com/example/spot/repository/PostRepository.java
  src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
  src/test/java/com/example/spot/service/post/PostQueryServiceTest.java
Labels: :1st_place_medal: deploy

#391 [MODIFY] 스터디 게시글 조회 시 좋아요/스크랩 확인 로직 추가
  src/main/java/com/example/spot/service/studypost/StudyPostQueryService.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :question: modify

#395 [MODIFY] 게시글 이미지 수정 로직 변경
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
Labels: :question: modify

#397 [FEATURE] 관심 지역 및 모집 중 스터디 조회 : 테마별 필터링 조건 추가
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestStudyDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestStudyWithThemeDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :+1: feature

#396 [MODIFY] 소셜 로그인 시, 반환되는 `isSpotMember` 판단 기준 변경
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
Labels: :question: modify

#398 Deploy 1.5.5
  src/main/java/com/example/spot/domain/Post.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/member/MemberServiceImpl.java
  src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryService.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryService.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
  src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestStudyDTO.java
  src/main/java/com/example/spot/web/dto/search/SearchRequestStudyWithThemeDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :1st_place_medal: deploy

#400 [MODIFY] 스터디 게시글 이미지 수정 로직 변경
  src/main/java/com/example/spot/domain/mapping/StudyPostImage.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
Labels: :question: modify

#402 [FEAT] 해당 서비스 가입 유무 조회 API 제작
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#403 Deploy 1.5.5
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/domain/mapping/StudyPostImage.java
  src/main/java/com/example/spot/domain/study/StudyPost.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/StudyPostController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
  src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
Labels: :1st_place_medal: deploy

#405 [FEAT] 닉네임 생성 및 약관 동의 API 응답에 `nickname` 추가
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#407 [MODIFY] 스터디 게시글 목록 조회 시 전체 페이지 수 반환
  src/main/java/com/example/spot/repository/StudyPostRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyPostRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyPostRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :question: modify

#408 Deploy 1.5.6
  src/main/java/com/example/spot/repository/StudyPostRepository.java
  src/main/java/com/example/spot/repository/querydsl/StudyPostRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyPostRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
  src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
Labels: :1st_place_medal: deploy

#410 [FEAT] 닉네임 중복 확인 API 구현
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :+1: feature

#414 [FEAT] 알림 조회 시, 알림이 발생한 지점으로 이동할 수 있도록 응답 값 추가
  src/main/java/com/example/spot/domain/Notification.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
Labels: :+1: feature

#415 Deploy 1.5.7
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
  src/main/java/com/example/spot/domain/Notification.java
  src/main/java/com/example/spot/repository/MemberRepository.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
  src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
  src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :1st_place_medal: deploy

#417 [MODIFY] 스터디 검색 필터링 조건 관련 개선
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
Labels: :+1: feature, :question: modify

#418 Deploy 1.5.8
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
Labels: :1st_place_medal: deploy

#420 [MODIFY] 참여중인 스터디 조회 쿼리 수정
  src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
  src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
  src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :question: modify
