Repository SPOTeam/Server, pull requests merged in 2025-01, with the labels that each got.

#292 [TEST] 스터디 조회 메서드 테스트 보강: 조건 브랜치 커버
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
Labels: :tada: test

#293 [TEST] 스터디 모집 및 신청 관련 조회 메서드 테스트 코드 작성
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
Labels: :tada: test

#295 [REFACTOR] 담당 API 엔드포인트 수정
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
Labels: :recycle: refactor

#296 [FIX] Fix Annotations and RequestMatchers
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/web/controller/AuthController.java
Labels: :hammer: fix

#297 Deploy 1.3.8
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/mapping/MemberStudy.java
  src/main/java/com/example/spot/domain/study/Schedule.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/ScheduleRequestDTO.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
  src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
  src/test/java/com/example/spot/service/studyschedule/StudyScheduleCommandServiceTest.java
  src/test/java/com/example/spot/service/studyschedule/StudyScheduleQueryServiceTest.java
Labels: :1st_place_medal: deploy

#299 [REFACTOR] 담당 API 엔드포인트 수정
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
Labels: :recycle: refactor

#301 [FEAT] 무중단 배포 도입 : Blue-Green 배포 적용
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/web/controller/UtilController.java
Labels: :+1: feature

#302 [FIX] 네이버 로그인에 대한 ExceptionAdvice 적용
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/web/controller/AuthController.java
Labels: :hammer: fix

#303 Deploy 1.3.9
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/service/auth/NaverOAuthService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/study/StudyCommandService.java
  src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/MemberStudyController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/controller/UtilController.java
Labels: :1st_place_medal: deploy

#304 [HOTFIX] 스크립트 문법 오류 정정
  .github/workflows/deploy.yml
Labels: :hammer: fix

#305 [HOTFIX] Workflow 스크립트 문법 오류 수정
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#306 [HOTFIX] 서버 상태 확인 전 대기 시간 추가
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#307 [HOTFIX] 서버 재가동 대기 시간 증가
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#308 [HOTFIX] 기존 고아 컨테이너 삭제 후 배포 하도록 수정
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#309 [FIX] Blue-Green 배포 위한 워크플로우 수정
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/web/controller/UtilController.java
Labels: :hammer: fix

#310 [HOTFIX] 배포 워크플로우 수정
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/web/controller/UtilController.java
Labels: :1st_place_medal: deploy

#311 [HOTFIX] 서버 환경 확인 URL 변경
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#312 [HOTFIX] 서버 재가동 대기 시간 30s -> 45s 증가
  .github/workflows/deploy.yml
Labels: :1st_place_medal: deploy

#313 [TEST] 스터디 출석체크 API 테스트 코드 작성
  src/main/java/com/example/spot/domain/mapping/MemberAttendance.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
  src/test/java/com/example/spot/service/studyattendance/StudyAttendanceCommandServiceTest.java
  src/test/java/com/example/spot/service/studyattendance/StudyAttendanceQueryServiceTest.java
Labels: :tada: test

#315 [REFACTOR] 담당 API 엔드포인트 수정
  src/main/java/com/example/spot/web/controller/PostController.java
Labels: :recycle: refactor

#317 [FIX] 배포 Workflow 및 Swagger 명세서 수정
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/web/controller/SearchController.java
Labels: :hammer: fix

#318 Deploy 1.3.10
  .github/workflows/deploy.yml
  src/main/java/com/example/spot/domain/mapping/MemberAttendance.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
  src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
  src/main/java/com/example/spot/web/controller/PostController.java
  src/main/java/com/example/spot/web/controller/SearchController.java
  src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
  src/test/java/com/example/spot/service/studyattendance/StudyAttendanceCommandServiceTest.java
  src/test/java/com/example/spot/service/studyattendance/StudyAttendanceQueryServiceTest.java
Labels: :1st_place_medal: deploy

#324 [FIX] 일반 회원가입 로직 수정
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :hammer: fix

#325 [HOTFIX] 일반 회원가입 로직 수정
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
Labels: :1st_place_medal: deploy

#328 [TEST] 알림, TODO 관련 서비스 테스트 코드 작성
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
  src/test/java/com/example/spot/service/notification/NotificationCommandServiceTest.java
  src/test/java/com/example/spot/service/notification/NotificationQueryServiceTest.java
Labels: :tada: test

#330 [FEAT] 로그인 API RSA 암호화 적용
  .gitignore
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/auth/RsaKey.java
  src/main/java/com/example/spot/repository/rsa/RSAKeyRepository.java
  src/main/java/com/example/spot/security/utils/RSAUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/rsa/Rsa.java
Labels: :+1: feature

#332 Deploy 1.3.11
  .gitignore
  src/main/java/com/example/spot/api/code/status/ErrorStatus.java
  src/main/java/com/example/spot/api/code/status/SuccessStatus.java
  src/main/java/com/example/spot/config/WebSecurity.java
  src/main/java/com/example/spot/domain/Region.java
  src/main/java/com/example/spot/domain/Theme.java
  src/main/java/com/example/spot/domain/auth/RsaKey.java
  src/main/java/com/example/spot/repository/rsa/RSAKeyRepository.java
  src/main/java/com/example/spot/security/utils/RSAUtils.java
  src/main/java/com/example/spot/service/auth/AuthService.java
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
  src/main/java/com/example/spot/web/controller/AuthController.java
  src/main/java/com/example/spot/web/controller/StudyController.java
  src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
  src/main/java/com/example/spot/web/dto/rsa/Rsa.java
  src/main/java/com/example/spot/web/dto/study/request/StudyJoinRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
  src/main/java/com/example/spot/web/dto/study/response/StudyJoinResponseDTO.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
  src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
  src/test/java/com/example/spot/service/notification/NotificationCommandServiceTest.java
  src/test/java/com/example/spot/service/notification/NotificationQueryServiceTest.java
  src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java
Labels: :1st_place_medal: deploy

#335 [MODIFY] 네이버 회원가입 프로필 이미지 변경
  src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
Labels: :question: modify
